language: node_js
sudo: false
cache:
  directories:
  - node_modules
  - version-0/node_modules
  - version-1/node_modules
  - version-2/node_modules
  - version-3/node_modules
node_js:
  - "0.10"
  - "0.12"
script: "npm run-script travis"
after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
